CREATE DATABASE crud_clientes CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

USE crud_clientes;

CREATE TABLE clientes (
    CLIENTE_ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_CLI VARCHAR(100) NOT NULL,
    DOMICILIO VARCHAR(150) NOT NULL,
    MAIL VARCHAR(100) NOT NULL,
    TELEFONO VARCHAR(20) NOT NULL
);
